name: build and test
on:
  pull_request:
    branches:
      - 'main'
jobs:
  gradle:
    runs-on: self-hosted
    permissions:
      contents: read
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive
    - name: Gradle assemble
      run: ./gradlew assemble
    - name: Gradle iOS test
      run: ./gradlew iosX64Test
    - name: Gradle Android test
      run: ./gradlew connectedAndroidTest
